AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: RAG Application Infrastructure
Parameters:
  KnowledgeBaseId:
    Type: String
    Default: SAZ2XA7OUY
    Description: ID of the existing Bedrock Knowledge Base
  AccountId:
    Type: String
    Description: AWS Account ID
  KnowledgeBaseBucket:
    Type: String
    Default: arn:aws:s3:::open-search-service
    Description: S3 bucket ARN for the knowledge base
  StackName:
    Type: String
    Description: Stack Name
Resources:
  CreateWebDataSourceLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: ${StackName}-create-web-data-source-lambda
      Runtime: nodejs18.x
      Handler: index.handler
      CodeUri: s3://centexautotitle.net/rag/services/86ae6b3f640181f70210bd9a0afb5c2d
      Timeout: 60
      Role:
        Fn::Sub: arn:aws:iam::${AccountId}:role/lambda-admin-role
      Events:
        CustomResource:
          Type: Api
          Properties:
            Path: /create-data-source
            Method: post
            RestApiId:
              Ref: KnowledgeBaseAPI
      Policies:
      - Statement:
        - Effect: Allow
          Action:
          - bedrock:CreateDataSource
          - bedrock:UpdateDataSource
          - bedrock:DeleteDataSource
          Resource: '*'
    Metadata:
      SamResourceId: CreateWebDataSourceLambda
  CreateWebDataSourceLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName:
        Fn::Sub: /aws/lambda/${StackName}-create-web-data-source-lambda
      RetentionInDays: 7
    Metadata:
      SamResourceId: CreateWebDataSourceLambdaLogGroup
  IngestLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: ${StackName}-ingest-lambda
      Runtime: nodejs20.x
      Handler: index.handler
      CodeUri: s3://centexautotitle.net/rag/services/74dfd1ea85b72d45195a8b4e79e5fa68
      Timeout: 900
      Role:
        Fn::Sub: arn:aws:iam::${AccountId}:role/lambda-admin-role
      Environment:
        Variables:
          BUCKET_ARN:
            Ref: KnowledgeBaseBucket
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /ingest
            Method: post
            RestApiId:
              Ref: KnowledgeBaseAPI
    Metadata:
      SamResourceId: IngestLambda
  IngestLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName:
        Fn::Sub: /aws/lambda/${StackName}-ingest-lambda
      RetentionInDays: 7
    Metadata:
      SamResourceId: IngestLambdaLogGroup
  QueryLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: ${StackName}-query-lambda
      Runtime: nodejs20.x
      Handler: index.handler
      CodeUri: s3://centexautotitle.net/rag/services/123eb436c573da498833b0dc6cf14d8a
      Timeout: 29
      Role:
        Fn::Sub: arn:aws:iam::${AccountId}:role/lambda-admin-role
      Environment:
        Variables:
          ACCOUNT_ID:
            Ref: AccountId
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /docs
            Method: post
            RestApiId:
              Ref: KnowledgeBaseAPI
      Policies:
      - Statement:
        - Effect: Allow
          Action:
          - bedrock:RetrieveAndGenerate
          - bedrock:Retrieve
          - bedrock:InvokeModel
          - bedrock:GetInferenceProfile
          Resource: '*'
    Metadata:
      SamResourceId: QueryLambda
  QueryLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName:
        Fn::Sub: /aws/lambda/${StackName}-query-lambda
      RetentionInDays: 7
    Metadata:
      SamResourceId: QueryLambdaLogGroup
  ListDataSourcesLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: ${StackName}-list-data-sources-lambda
      Runtime: nodejs20.x
      Handler: index.handler
      CodeUri: s3://centexautotitle.net/rag/services/f63b668755ed1a545dfde7900b5b4aef
      Timeout: 900
      Role:
        Fn::Sub: arn:aws:iam::${AccountId}:role/lambda-admin-role
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /data-sources
            Method: get
            RestApiId:
              Ref: KnowledgeBaseAPI
    Metadata:
      SamResourceId: ListDataSourcesLambda
  ListDataSourcesLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName:
        Fn::Sub: /aws/lambda/${StackName}-list-data-sources-lambda
      RetentionInDays: 7
    Metadata:
      SamResourceId: ListDataSourcesLambdaLogGroup
  CreateChatBotLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: ${StackName}-create-chat-bot-lambda
      Runtime: nodejs20.x
      Handler: index.handler
      CodeUri: s3://centexautotitle.net/rag/services/e5ea30b03b8e35b0514a48d8631021b1
      Timeout: 900
      Role:
        Fn::Sub: arn:aws:iam::${AccountId}:role/lambda-admin-role
      Environment:
        Variables:
          CHATBOT_TABLE_NAME:
            Ref: ChatbotTable
          KNOWLEDGE_BASE_ROLE_ARN: arn:aws:iam::905418372486:role/service-role/AmazonBedrockExecutionRoleForKnowledgeBase_9umgz
          EMBEDDING_MODEL_ARN: arn:aws:bedrock:us-east-1::foundation-model/amazon.titan-embed-text-v2:0
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /chatbot
            Method: post
            RestApiId:
              Ref: KnowledgeBaseAPI
    Metadata:
      SamResourceId: CreateChatBotLambda
  CreateChatBotLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName:
        Fn::Sub: /aws/lambda/${StackName}-create-chat-bot-lambda
      RetentionInDays: 7
    Metadata:
      SamResourceId: CreateChatBotLambdaLogGroup
  ChatbotTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName:
        Fn::Sub: ${StackName}-rag-chatbot-table
      AttributeDefinitions:
      - AttributeName: chatBotId
        AttributeType: S
      KeySchema:
      - AttributeName: chatBotId
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
    Metadata:
      SamResourceId: ChatbotTable
  KnowledgeBaseTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName:
        Fn::Sub: ${StackName}-rag-knowledge-base-table
      AttributeDefinitions:
      - AttributeName: knowledgeBaseId
        AttributeType: S
      - AttributeName: chatBotId
        AttributeType: S
      KeySchema:
      - AttributeName: knowledgeBaseId
        KeyType: HASH
      - AttributeName: chatBotId
        KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
    Metadata:
      SamResourceId: KnowledgeBaseTable
  KnowledgeBaseAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      Name:
        Fn::Sub: ${StackName}-knowledgebase-api
      EndpointConfiguration:
        Type: REGIONAL
      Cors:
        AllowMethods: '''*'''
        AllowHeaders: '''*'''
        AllowOrigin: '''*'''
    Metadata:
      SamResourceId: KnowledgeBaseAPI
Outputs:
  ApiGatewayUrl:
    Description: API Gateway URL
    Value:
      Fn::Sub: https://${KnowledgeBaseAPI}.execute-api.${AWS::Region}.amazonaws.com/dev
