AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: RAG Application Infrastructure
Parameters:
  KnowledgeBaseId:
    Type: String
    Default: SAZ2XA7OUY
    Description: ID of the existing Bedrock Knowledge Base
  AccountId:
    Type: String
    Description: AWS Account ID
  KnowledgeBaseBucket:
    Type: String
    Default: arn:aws:s3:::open-search-service
    Description: S3 bucket ARN for the knowledge base
  StackName:
    Type: String
    Description: Stack Name
Resources:
  CommonLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName:
        Fn::Sub: ${StackName}-common-layer
      Description: Common utilities and services for all Lambda functions
      ContentUri: s3://centexautotitle.net/rag/services/11e8928b5b067ae00e83685e3f3bbc94
      CompatibleRuntimes:
      - nodejs20.x
      RetentionPolicy: Delete
    Metadata:
      SamResourceId: CommonLayer
  DependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName:
        Fn::Sub: ${StackName}-dependencies-layer
      Description: Dependencies layer for the Bedrock RAG project
      ContentUri: s3://centexautotitle.net/rag/services/f329c41d42e3e3fb5a564cf9b05ce349
      CompatibleRuntimes:
      - nodejs20.x
      RetentionPolicy: Delete
    Metadata:
      SamResourceId: DependenciesLayer
  QueryLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: ${StackName}-query-lambda
      Runtime: nodejs20.x
      Handler: index.handler
      CodeUri: s3://centexautotitle.net/rag/services/4e6b808960ff3ab6384f792670a79545
      Timeout: 29
      Role:
        Fn::Sub: arn:aws:iam::${AccountId}:role/lambda-admin-role
      Environment:
        Variables:
          ACCOUNT_ID:
            Ref: AccountId
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /docs
            Method: post
            RestApiId:
              Ref: KnowledgeBaseAPI
      Policies:
      - Statement:
        - Effect: Allow
          Action:
          - bedrock:RetrieveAndGenerate
          - bedrock:Retrieve
          - bedrock:InvokeModel
          - bedrock:GetInferenceProfile
          Resource: '*'
    Metadata:
      SamResourceId: QueryLambda
  QueryLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName:
        Fn::Sub: /aws/lambda/${StackName}-query-lambda
      RetentionInDays: 7
    Metadata:
      SamResourceId: QueryLambdaLogGroup
  ListDataSourcesLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: ${StackName}-list-data-sources-lambda
      Runtime: nodejs20.x
      Handler: index.handler
      CodeUri: s3://centexautotitle.net/rag/services/6047208301d7b5fc07a26f805c07d425
      Timeout: 900
      Role:
        Fn::Sub: arn:aws:iam::${AccountId}:role/lambda-admin-role
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /data-sources
            Method: get
            RestApiId:
              Ref: KnowledgeBaseAPI
    Metadata:
      SamResourceId: ListDataSourcesLambda
  ListDataSourcesLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName:
        Fn::Sub: /aws/lambda/${StackName}-list-data-sources-lambda
      RetentionInDays: 7
    Metadata:
      SamResourceId: ListDataSourcesLambdaLogGroup
  CreateChatBotLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: ${StackName}-create-chat-bot-lambda
      Runtime: nodejs20.x
      Handler: index.handler
      CodeUri: s3://centexautotitle.net/rag/services/c2dbf9b2165385dda7811d38676af684
      Timeout: 900
      Role:
        Fn::Sub: arn:aws:iam::${AccountId}:role/lambda-admin-role
      Layers:
      - Ref: CommonLayer
      - Ref: DependenciesLayer
      Environment:
        Variables:
          NODE_PATH: /opt/nodejs:/opt/nodejs/node_modules:/opt/common:/opt/dependencies
          CHATBOT_TABLE_NAME:
            Ref: ChatbotTable
          USER_TABLE_NAME:
            Ref: UserDetailsTable
          USER_CHATBOT_TABLE_NAME:
            Ref: UserChatBotTable
          KNOWLEDGE_BASE_ROLE_ARN: arn:aws:iam::905418372486:role/service-role/AmazonBedrockExecutionRoleForKnowledgeBase_9umgz
          EMBEDDING_MODEL_ARN: arn:aws:bedrock:us-east-1::foundation-model/amazon.titan-embed-text-v2:0
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /chatbot
            Method: post
            RestApiId:
              Ref: KnowledgeBaseAPI
    Metadata:
      SamResourceId: CreateChatBotLambda
  CreateChatBotLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName:
        Fn::Sub: /aws/lambda/${StackName}-create-chat-bot-lambda
      RetentionInDays: 7
    Metadata:
      SamResourceId: CreateChatBotLambdaLogGroup
  UserSignUpLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: ${StackName}-user-sign-up-lambda
      Runtime: nodejs20.x
      Handler: index.handler
      CodeUri: s3://centexautotitle.net/rag/services/2a28835b413e870141a54ee81189d4ff
      Timeout: 900
      Role:
        Fn::Sub: arn:aws:iam::${AccountId}:role/lambda-admin-role
      Layers:
      - Ref: CommonLayer
      - Ref: DependenciesLayer
      Environment:
        Variables:
          NODE_PATH: /opt/nodejs:/opt/nodejs/node_modules:/opt/common:/opt/dependencies
          USERS_TABLE_NAME:
            Ref: UserDetailsTable
          KNOWLEDGE_BASE_ROLE_ARN: arn:aws:iam::905418372486:role/service-role/AmazonBedrockExecutionRoleForKnowledgeBase_9umgz
          EMBEDDING_MODEL_ARN: arn:aws:bedrock:us-east-1::foundation-model/amazon.titan-embed-text-v2:0
          S3_BUCKET_NAME: open-search-service
          INTERMEDIATE_BUCKET_NAME: intermediate-open-service
          OPEN_SEARCH_SERVICE_COLLECTION_ID: '0zvm36wbjq6vn7yjsz44'
          KNOWLEDGE_BASE_TABLE_NAME:
            Ref: KnowledgeBaseTable
          AWS_ACCOUNT_ID:
            Ref: AccountId
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /user-sign-up
            Method: post
            RestApiId:
              Ref: KnowledgeBaseAPI
    Metadata:
      SamResourceId: UserSignUpLambda
  UserSignUpLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName:
        Fn::Sub: /aws/lambda/${StackName}-user-sign-up-lambda
      RetentionInDays: 7
    Metadata:
      SamResourceId: UserSignUpLambdaLogGroup
  GetAllChatBotsLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: ${StackName}-get-all-chatbots-lambda
      Runtime: nodejs20.x
      Handler: index.handler
      CodeUri: s3://centexautotitle.net/rag/services/c73501d6250ce03ce71c9406a7e03c3f
      Timeout: 900
      Role:
        Fn::Sub: arn:aws:iam::${AccountId}:role/lambda-admin-role
      Layers:
      - Ref: CommonLayer
      - Ref: DependenciesLayer
      Environment:
        Variables:
          NODE_PATH: /opt/nodejs:/opt/nodejs/node_modules:/opt/common:/opt/dependencies
          CHATBOT_TABLE_NAME:
            Ref: ChatbotTable
          USER_TABLE_NAME:
            Ref: UserDetailsTable
          USER_CHATBOT_TABLE_NAME:
            Ref: UserChatBotTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /chatbots
            Method: get
            RestApiId:
              Ref: KnowledgeBaseAPI
    Metadata:
      SamResourceId: GetAllChatBotsLambda
  GetAllChatBotsLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName:
        Fn::Sub: /aws/lambda/${StackName}-get-all-chatbots-lambda
      RetentionInDays: 7
    Metadata:
      SamResourceId: GetAllChatBotsLambdaLogGroup
  GenerateSignedUrlLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: ${StackName}-generate-signed-url-lambda
      Runtime: nodejs20.x
      Handler: index.handler
      CodeUri: s3://centexautotitle.net/rag/services/4494b46081319b66ff903d475090a065
      Timeout: 900
      Role:
        Fn::Sub: arn:aws:iam::${AccountId}:role/lambda-admin-role
      Layers:
      - Ref: CommonLayer
      - Ref: DependenciesLayer
      Environment:
        Variables:
          NODE_PATH: /opt/nodejs:/opt/nodejs/node_modules:/opt/common:/opt/dependencies
          BUCKET_NAME: open-search-service
          CHATBOT_TABLE_NAME:
            Ref: ChatbotTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /generate-signed-url
            Method: post
            RestApiId:
              Ref: KnowledgeBaseAPI
    Metadata:
      SamResourceId: GenerateSignedUrlLambda
  GenerateSignedUrlLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName:
        Fn::Sub: /aws/lambda/${StackName}-generate-signed-url-lambda
      RetentionInDays: 7
    Metadata:
      SamResourceId: GenerateSignedUrlLambdaLogGroup
  StartIngestionLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: ${StackName}-start-ingestion-lambda
      Runtime: nodejs20.x
      Handler: index.handler
      CodeUri: s3://centexautotitle.net/rag/services/f848f3fd5e87e45affa38afc611aba51
      Timeout: 900
      Role:
        Fn::Sub: arn:aws:iam::${AccountId}:role/lambda-admin-role
      Layers:
      - Ref: CommonLayer
      - Ref: DependenciesLayer
      Environment:
        Variables:
          NODE_PATH: /opt/nodejs:/opt/nodejs/node_modules:/opt/common:/opt/dependencies
          USER_TABLE_NAME:
            Ref: UserDetailsTable
          USER_CHATBOT_TABLE_NAME:
            Ref: UserChatBotTable
          KNOWLEDGE_BASE_TABLE_NAME:
            Ref: KnowledgeBaseTable
          CHATBOT_TABLE_NAME:
            Ref: ChatbotTable
          INGESTION_JOB_TABLE_NAME:
            Ref: IngestionJobTable
          BEDROCK_MODEL_ARN: arn:aws:bedrock:us-east-1::foundation-model/amazon.titan-embed-text-v2:0
          S3_BUCKET_NAME: open-search-service
          AWS_ACCOUNT_ID:
            Ref: AccountId
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /ingest
            Method: post
            RestApiId:
              Ref: KnowledgeBaseAPI
    Metadata:
      SamResourceId: StartIngestionLambda
  StartIngestionLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName:
        Fn::Sub: /aws/lambda/${StackName}-start-ingestion-lambda
      RetentionInDays: 7
    Metadata:
      SamResourceId: StartIngestionLambdaLogGroup
  CreateDataSourceLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: ${StackName}-create-data-source-lambda
      Runtime: nodejs20.x
      Handler: index.handler
      CodeUri: s3://centexautotitle.net/rag/services/4825c09e18eaaa8dbd99b8ca4c363a7e
      Timeout: 900
      Role:
        Fn::Sub: arn:aws:iam::${AccountId}:role/lambda-admin-role
      Layers:
      - Ref: CommonLayer
      - Ref: DependenciesLayer
      Environment:
        Variables:
          NODE_PATH: /opt/nodejs:/opt/nodejs/node_modules:/opt/common:/opt/dependencies
          USER_TABLE_NAME:
            Ref: UserDetailsTable
          USER_CHATBOT_TABLE_NAME:
            Ref: UserChatBotTable
          KNOWLEDGE_BASE_TABLE_NAME:
            Ref: KnowledgeBaseTable
          TRANSFORM_DOCUMENTS_LAMBDA_ARN:
            Fn::GetAtt:
            - TransformDocumentsLambda
            - Arn
          INTERMEDIATE_BUCKET_NAME: intermediate-open-service
          CHATBOT_TABLE_NAME:
            Ref: ChatbotTable
          BEDROCK_MODEL_ARN: arn:aws:bedrock:us-east-1::foundation-model/amazon.titan-embed-text-v2:0
          S3_BUCKET_NAME: open-search-service
          AWS_ACCOUNT_ID:
            Ref: AccountId
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /data-source
            Method: post
            RestApiId:
              Ref: KnowledgeBaseAPI
    Metadata:
      SamResourceId: CreateDataSourceLambda
  CreateDataSourceLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName:
        Fn::Sub: /aws/lambda/${StackName}-create-data-source-lambda
      RetentionInDays: 7
    Metadata:
      SamResourceId: CreateDataSourceLambdaLogGroup
  TransformDocumentsLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: ${StackName}-transform-documents-lambda
      Runtime: nodejs20.x
      Handler: index.handler
      CodeUri: s3://centexautotitle.net/rag/services/3db13b0e60f7c88290d554655a5e96c8
      Timeout: 900
      Role:
        Fn::Sub: arn:aws:iam::${AccountId}:role/lambda-admin-role
      Layers:
      - Ref: CommonLayer
      - Ref: DependenciesLayer
      Environment:
        Variables:
          NODE_PATH: /opt/nodejs:/opt/nodejs/node_modules:/opt/common:/opt/dependencies
          S3_BUCKET_NAME: open-search-service
    Metadata:
      SamResourceId: TransformDocumentsLambda
  TransformDocumentsLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName:
        Fn::Sub: /aws/lambda/${StackName}-transform-documents-lambda
      RetentionInDays: 7
    Metadata:
      SamResourceId: TransformDocumentsLambdaLogGroup
  ChatbotTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName:
        Fn::Sub: ${StackName}-chatbot-table
      AttributeDefinitions:
      - AttributeName: chatBotId
        AttributeType: S
      KeySchema:
      - AttributeName: chatBotId
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
    Metadata:
      SamResourceId: ChatbotTable
  KnowledgeBaseTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName:
        Fn::Sub: ${StackName}-knowledge-base-table
      AttributeDefinitions:
      - AttributeName: knowledgeBaseId
        AttributeType: S
      - AttributeName: createdBy
        AttributeType: S
      KeySchema:
      - AttributeName: knowledgeBaseId
        KeyType: HASH
      - AttributeName: createdBy
        KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
    Metadata:
      SamResourceId: KnowledgeBaseTable
  UserDetailsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName:
        Fn::Sub: ${StackName}-user-details-table
      AttributeDefinitions:
      - AttributeName: userId
        AttributeType: S
      KeySchema:
      - AttributeName: userId
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 10
        WriteCapacityUnits: 10
    Metadata:
      SamResourceId: UserDetailsTable
  UserChatBotTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName:
        Fn::Sub: ${StackName}-user-chatbot-table
      AttributeDefinitions:
      - AttributeName: userId
        AttributeType: S
      - AttributeName: chatBotId
        AttributeType: S
      - AttributeName: createdBy
        AttributeType: S
      KeySchema:
      - AttributeName: userId
        KeyType: HASH
      - AttributeName: chatBotId
        KeyType: RANGE
      GlobalSecondaryIndexes:
      - IndexName: createdBy-index
        KeySchema:
        - AttributeName: createdBy
          KeyType: HASH
        Projection:
          ProjectionType: ALL
        ProvisionedThroughput:
          ReadCapacityUnits: 10
          WriteCapacityUnits: 10
      ProvisionedThroughput:
        ReadCapacityUnits: 10
        WriteCapacityUnits: 10
    Metadata:
      SamResourceId: UserChatBotTable
  IngestionJobTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName:
        Fn::Sub: ${StackName}-ingestion-job-table
      AttributeDefinitions:
      - AttributeName: jobId
        AttributeType: S
      - AttributeName: createdBy
        AttributeType: S
      KeySchema:
      - AttributeName: jobId
        KeyType: HASH
      GlobalSecondaryIndexes:
      - IndexName: createdBy-index
        KeySchema:
        - AttributeName: createdBy
          KeyType: HASH
        Projection:
          ProjectionType: ALL
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
    Metadata:
      SamResourceId: IngestionJobTable
  KnowledgeBaseAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      Name:
        Fn::Sub: ${StackName}-knowledgebase-api
      EndpointConfiguration:
        Type: REGIONAL
      Cors:
        AllowMethods: '''*'''
        AllowHeaders: '''*'''
        AllowOrigin: '''*'''
    Metadata:
      SamResourceId: KnowledgeBaseAPI
Outputs:
  ApiGatewayUrl:
    Description: API Gateway URL
    Value:
      Fn::Sub: https://${KnowledgeBaseAPI}.execute-api.${AWS::Region}.amazonaws.com/dev
